name: Build and Test

on: [push, pull_request]

jobs:
  build-and-test:
    name: python
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6

      - name: Read Python version
        id: read-python-version
        run: |
          echo "PY_VER=$(cat .python_version)" >> $GITHUB_ENV

      - name: Install Python (uv)
        run: uv python install $PY_VER

      - name: Install packages
        run: uv sync --upgrade --all-extras

      - name: Run unit tests
        run: uv run python -m unittest discover -v